spring:
  datasource:
      username: root
      password: 1234
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/customers
mybatis:
  mapper-locations: classpath:sqlmap/UserMapper.xml
  type-aliases-package: org.springboot.sample.entity
